# Generated by Django 5.2.1 on 2025-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='schedule',
        ),
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3),
        ),
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
