# Generated by Django 5.2.1 on 2025-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_classroom_class_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
