# Generated by Django 5.2.1 on 2025-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_user'),
        ('classroom', '0004_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_classes', to='accounts.studentprofile'),
        ),
    ]
